version: '3.9'
services:
  mysql:
    image: 'mysql:latest'
    restart: always
    volumes:
      - './mysql_data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - '3306:3306'